name: e2e
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.rs'
      - '**.go'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/e2e.yml'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54
          args: --timeout 5m
          working-directory: e2e/interchaintest
  build:
    strategy:
      fail-fast: false
      matrix:
        test:
          - TestWithContractTestSuite/TestIcaContractChannelHandshake_Ordered_Protobuf
          - TestWithContractTestSuite/TestIcaContractChannelHandshake_Unordered_Protobuf
          - TestWithContractTestSuite/TestIcaRelayerInstantiatedChannelHandshake
          - TestWithContractTestSuite/TestRecoveredIcaContractInstantiatedChannelHandshake
          - TestWithContractTestSuite/TestIcaContractExecution_Ordered_Protobuf
          - TestWithContractTestSuite/TestIcaContractExecution_Unordered_Protobuf
          - TestWithContractTestSuite/TestIcaContractTimeoutPacket_Ordered_Protobuf
          - TestWithContractTestSuite/TestIcaContractTimeoutPacket_Unordered_Protobuf
          - TestWithOwnerTestSuite/TestOwnerCreateIcaContract
          - TestWithOwnerTestSuite/TestOwnerPredefinedAction
          - TestWithContractTestSuite/TestSendCosmosMsgs_Ordered_Protobuf
          - TestWithContractTestSuite/TestSendCosmosMsgs_Unordered_Protobuf
          - TestWithContractTestSuite/TestSendWasmMsgsProtobufEncoding
          - TestWithContractTestSuite/TestMigrateOrderedToUnordered
          - TestWithContractTestSuite/TestCloseChannel_Protobuf_Unordered
    name: ${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Build Test Contracts with Docker
        run: just build-test-contracts
      - name: Build Optimized Contract
        run: just build-optimize
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
          cache-dependency-path: |
             e2e/interchaintest/go.sum
      - name: TestContract
        run: |
          cd e2e/interchaintest
          go test -v . -run=${{ matrix.test }}
      - name: Upload Diagnostics on Failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        continue-on-error: true
        with:
          name: '${{ matrix.entrypoint }}-${{ matrix.test }}'
          path: e2e/diagnostics
          retention-days: 5
